name: Setup Rust
description: 'Setup Rust toolchain with caching'

inputs:
  toolchain:
    description: 'Rust toolchain version'
    default: 'stable'
  components:
    description: 'Additional components to install (comma-separated)'
    default: ''
  targets:
    description: 'Additional targets to install (comma-separated)'
    default: ''
  cache-key:
    description: 'Additional cache key suffix'
    default: ''

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.cache-key }}

